---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{.Release.Name}}-subscription-server
  labels:
    operator.sme.sap.com/app: subscription-server
    operator.sme.sap.com/category: controller
    operator.sme.sap.com/release: {{.Release.Name}}
spec:
  replicas: {{.Values.subscriptionServer.replicas}}
  selector:
    matchLabels:
      operator.sme.sap.com/app: subscription-server
      operator.sme.sap.com/category: controller
      operator.sme.sap.com/release: {{.Release.Name}}
  template:
    metadata:
      labels:
        operator.sme.sap.com/app: subscription-server
        operator.sme.sap.com/category: controller
        operator.sme.sap.com/release: {{.Release.Name}}
        {{- if or (gt (len .Values.podLabels) 0) (gt (len .Values.subscriptionServer.podLabels) 0) }}
        {{- include "utils.maps.merge" (list .Values.podLabels .Values.subscriptionServer.podLabels) | trim | nindent 8 }}
        {{- end }}
      {{- if or (gt (len .Values.podAnnotations) 0) (gt (len .Values.subscriptionServer.podAnnotations) 0) }}
      annotations:
        {{- include "utils.maps.merge" (list .Values.podAnnotations .Values.subscriptionServer.podAnnotations) | trim | nindent 8 }}
      {{- end }}
    spec:
      {{- with .Values.subscriptionServer.imagePullSecrets | default .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.subscriptionServer.podSecurityContext | default .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.subscriptionServer.nodeSelector | default .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.subscriptionServer.affinity | default .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.subscriptionServer.tolerations | default .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.subscriptionServer.priorityClassName | default .Values.priorityClassName }}
      priorityClassName: {{ . }}
      {{- end }}
      {{- with .Values.subscriptionServer.topologySpreadConstraints | default .Values.topologySpreadConstraints }}
      topologySpreadConstraints:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if or .Values.subscriptionServer.volumes .Values.subscriptionServer.certManager.enabled }}
      volumes:
        {{- with .Values.subscriptionServer.volumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- if .Values.subscriptionServer.certManager.enabled }}
        - name: ssl
          secret:
            secretName: {{.Release.Name}}-subscription-server-tls-managed
            items:
            - key: tls.key
              path: tls.key
            - key: tls.crt
              path: tls.crt
        {{- end }}
      {{- end }}
      containers:
        - name: server
          image: {{ .Values.subscriptionServer.image.repository }}:{{ .Values.subscriptionServer.image.tag | default .Values.image.tag | default .Chart.AppVersion }}
          imagePullPolicy: {{ .Values.subscriptionServer.image.pullPolicy | default .Values.image.pullPolicy }}
          {{- with .Values.subscriptionServer.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.subscriptionServer.resources | nindent 12 }}
          {{- if .Values.subscriptionServer.certManager.enabled }}
          env:
            - name: TLS_ENABLED
              value: "true"
            - name: TLS_KEY
              value: "/app/etc/ssl/tls.key"
            - name: TLS_CERT
              value: "/app/etc/ssl/tls.crt"
          {{- end }}
          {{- if or .Values.subscriptionServer.volumeMounts .Values.subscriptionServer.certManager.enabled }}
          volumeMounts:
            {{- with .Values.subscriptionServer.volumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
            {{- if .Values.subscriptionServer.certManager.enabled }}
            - name: ssl
              mountPath: /app/etc/ssl
            {{- end }}
          {{- end }}
          ports:
            - name: server-port
              containerPort: 4000
              protocol: TCP
            - name: metrics-port
              containerPort: 9090
              protocol: TCP
      serviceAccountName: {{.Release.Name}}-subscription-server
---
kind: Service
apiVersion: v1
metadata:
  name: {{.Release.Name}}-subscription-server
  labels:
    operator.sme.sap.com/app: subscription-server
    operator.sme.sap.com/category: controller
    operator.sme.sap.com/release: {{.Release.Name}}
spec:
  ports:
    - name: sub-server-port
      protocol: TCP
      port: {{.Values.subscriptionServer.port}}
      targetPort: server-port
    - name: metrics-http
      protocol: TCP
      port: 9090
      targetPort: metrics-port
  selector:
    operator.sme.sap.com/app: subscription-server
    operator.sme.sap.com/category: controller
    operator.sme.sap.com/release: {{.Release.Name}}
---
{{- if .Values.monitoring.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{.Release.Name}}-subscription-server
  labels:
    operator.sme.sap.com/app: subscription-server
    operator.sme.sap.com/category: controller
    operator.sme.sap.com/release: {{.Release.Name}}
spec:
  selector:
    matchLabels:
      operator.sme.sap.com/app: subscription-server
      operator.sme.sap.com/category: controller
  endpoints:
  - port: metrics-http
{{- end }}
