{{- if and (gt (int .Values.subscriptionServer.replicas) 0) .Values.subscriptionServer.certManager.enabled }}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{.Release.Name}}-subscription-server-cert
  labels:
    operator.sme.sap.com/app: subscription-server
    operator.sme.sap.com/category: controller
    operator.sme.sap.com/release: {{.Release.Name}}
spec:
  commonName: {{.Values.subscriptionServer.domain}}
  duration: 3650h
  issuerRef:
    {{- with .Values.subscriptionServer.certManager.issuerGroup }}
    group: {{ . }}
    {{- end }}
    {{- with .Values.subscriptionServer.certManager.issuerKind }}
    kind: {{ . }}
    {{- end }}
    {{- with .Values.subscriptionServer.certManager.issuerName }}
    name: {{ . }}
    {{- end }}
  secretName: {{.Release.Name}}-subscription-server-tls-managed
{{- end }}
