apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/name: cap-operator-leader-election-rolebinding
    app.kubernetes.io/instance: cap-operator-leader-election-rolebinding
    app.kubernetes.io/component: rbac
  name: cap-operator-leader-election-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: cap-operator-leader-election-role
subjects:
- kind: ServiceAccount
  name: cap-operator-controller-manager
  namespace: system
