apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/name: cap-operator-manager-rolebinding
    app.kubernetes.io/instance: cap-operator-manager-rolebinding
    app.kubernetes.io/component: rbac
  name: cap-operator-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cap-operator-manager-role
subjects:
- kind: ServiceAccount
  name: cap-operator-controller-manager
  namespace: system
