//go:build !ignore_autogenerated

/*
SPDX-FileCopyrightText: 2023 SAP SE or an SAP affiliate company and cap-operator-lifecycle contributors
SPDX-License-Identifier: Apache-2.0
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CAPOperator) DeepCopyInto(out *CAPOperator) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CAPOperator.
func (in *CAPOperator) DeepCopy() *CAPOperator {
	if in == nil {
		return nil
	}
	out := new(CAPOperator)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CAPOperator) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CAPOperatorList) DeepCopyInto(out *CAPOperatorList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CAPOperator, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CAPOperatorList.
func (in *CAPOperatorList) DeepCopy() *CAPOperatorList {
	if in == nil {
		return nil
	}
	out := new(CAPOperatorList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CAPOperatorList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CAPOperatorSpec) DeepCopyInto(out *CAPOperatorSpec) {
	*out = *in
	out.SubscriptionServer = in.SubscriptionServer
	out.IngressGatewayLabels = in.IngressGatewayLabels
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CAPOperatorSpec.
func (in *CAPOperatorSpec) DeepCopy() *CAPOperatorSpec {
	if in == nil {
		return nil
	}
	out := new(CAPOperatorSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CAPOperatorStatus) DeepCopyInto(out *CAPOperatorStatus) {
	*out = *in
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CAPOperatorStatus.
func (in *CAPOperatorStatus) DeepCopy() *CAPOperatorStatus {
	if in == nil {
		return nil
	}
	out := new(CAPOperatorStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IngressGatewayLabels) DeepCopyInto(out *IngressGatewayLabels) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IngressGatewayLabels.
func (in *IngressGatewayLabels) DeepCopy() *IngressGatewayLabels {
	if in == nil {
		return nil
	}
	out := new(IngressGatewayLabels)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SubscriptionServer) DeepCopyInto(out *SubscriptionServer) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SubscriptionServer.
func (in *SubscriptionServer) DeepCopy() *SubscriptionServer {
	if in == nil {
		return nil
	}
	out := new(SubscriptionServer)
	in.DeepCopyInto(out)
	return out
}
