{
 "title": "CAP Operator - Info",
 "tags": [ "cap-operator" ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "duration",
    "label": "Duration",
    "query": "24 hours : 24h, 30 days : 30d, 90 days : 90d, 1 year : 1y"
   }
  ]
 },
 "panels": [
  { "title": "CAP Operator Lifecycle", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "duration" },
  {
   "title": "Lifecycle Operations - $duration",
   "type": "stat",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ceil(sum(increase((cap_op_tenant_operations{}[$duration]))))",
     "legendFormat": "Tenant Ops"
    },
    {
     "expr": "ceil(sum(increase((cap_op_service_operations{}[$duration]))))",
     "legendFormat": "Service Ops"
    }
   ]
  },
  {
   "title": "Provisioning - $duration",
   "type": "stat",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ceil(sum(increase((cap_op_tenant_operations{operation=\"provisioning\"}[$duration]))))",
     "legendFormat": "$duration"
    }
   ]
  },
  {
   "title": "Lifecycle Failures - $duration",
   "type": "stat",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(increase(cap_op_tenant_operation_failures{}[$duration]))",
     "legendFormat": "$duration"
    }
   ]
  },
  {
   "title": "Tenant Operation Failures",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "increase(cap_op_tenant_operation_failures{}[$duration])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "System Info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "Controller - Replicas",
     "type": "stat",
     "gridPos": { "h": 7, "w": 3, "x": 0, "y": 22 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "kube_deployment_spec_replicas{namespace=\"cap-system\",deployment=\"cap-operator-controller\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Controller Restarts",
     "type": "gauge",
     "gridPos": { "h": 7, "w": 3, "x": 3, "y": 22 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_pod_container_status_restarts_total{namespace=\"cap-system\",container=\"controller\"})",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}